#!/usr/bin/env bash

set -euo pipefail

if [ $# -lt 2 ]; then
  echo "Usage: $0 <TASK_ID> <TASK_TITLE> [feature|bugfix]"
  echo "Example: $0 MKT-102 \"Product recommendation engine\" feature"
  exit 1
fi

TASK_ID="$1"
TASK_TITLE="$2"
TASK_TYPE="${3:-feature}"

slugify() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9]/-/g' \
    | sed 's/-\{2,\}/-/g' \
    | sed 's/^-//' \
    | sed 's/-$//'
}

BRANCH_SLUG="$(slugify "$TASK_TITLE")"
BRANCH_NAME="${TASK_TYPE}/${TASK_ID}-${BRANCH_SLUG}"

DATE_NOW="$(date '+%Y-%m-%d %H:%M:%S')"

CLAUDE_DIR="docs/claude-usage"
DELIVERY_DIR="docs/delivery"
PR_DIR="pull_requests"

CLAUDE_FILE="${CLAUDE_DIR}/${TASK_ID}.md"
DELIVERY_FILE="${DELIVERY_DIR}/${TASK_ID}.md"
PR_FILE="${PR_DIR}/${TASK_ID}.md"

mkdir -p "$CLAUDE_DIR" "$DELIVERY_DIR" "$PR_DIR"

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git checkout -b "$BRANCH_NAME"
else
  echo "Warning: Not inside a git repository. Files will still be created."
fi

if [ ! -f "$CLAUDE_FILE" ]; then
cat > "$CLAUDE_FILE" <<EOF
# Claude Usage Log

## Task ID
${TASK_ID}

## Task Title
${TASK_TITLE}

## Branch
${BRANCH_NAME}

## Status
In Progress

## Usage Entries

### Entry 1
- Date: ${DATE_NOW}
- Purpose: Initial task setup
- Prompt Summary: Started task scaffolding and documentation generation
- Output generated by Claude:
  - Created SOP tracking files
  - Prepared initial templates for Claude usage, delivery note, and PR
- Files impacted:
  - ${CLAUDE_FILE}
  - ${DELIVERY_FILE}
  - ${PR_FILE}
- What was manually modified:
  - Replace this line with your manual changes
- What was manually verified:
  - Replace this line with what you verified manually
- Risk/notes:
  - Update this file whenever Claude is used for implementation, debugging, refactoring, or documentation
EOF
fi

if [ ! -f "$DELIVERY_FILE" ]; then
cat > "$DELIVERY_FILE" <<EOF
# Feature Delivery Note

## Task ID
${TASK_ID}

## Feature
${TASK_TITLE}

## Branch
${BRANCH_NAME}

## Status
In Progress

## What was built
Describe what was built.

## How it works
Explain the main logic flow.

## Inputs
- Add inputs here

## Outputs
- Add outputs here

## Dependencies
- Add dependencies here

## Files Changed
- Add changed files here

## Testing
- Tested locally: No
- Edge cases covered:
  - Add edge cases here

## Known Limitations
- Add limitations here

## Follow-up Items
- Add follow-up tasks here

## Notes
- Add extra implementation notes here
EOF
fi

if [ ! -f "$PR_FILE" ]; then
cat > "$PR_FILE" <<EOF
## Task Link
${TASK_ID}

## Summary
Describe what was implemented.

## Claude Usage
- Used: Yes
- Purpose:
- Output generated:
- What was manually verified/modified:

## Changes Made
- Change 1
- Change 2

## Testing
- Tested locally: No
- Edge cases covered:

## Screenshots / Demo (if applicable)

## Checklist
- [ ] Code reviewed by self
- [ ] No unnecessary code
- [ ] Proper naming conventions
EOF
fi

echo ""
echo "Task setup complete."
echo "Branch: ${BRANCH_NAME}"
echo "Created/verified:"
echo "  - ${CLAUDE_FILE}"
echo "  - ${DELIVERY_FILE}"
echo "  - ${PR_FILE}"
echo ""
echo "Next steps:"
echo "  1. Start coding in branch ${BRANCH_NAME}"
echo "  2. Update ${CLAUDE_FILE} whenever Claude is used"
echo "  3. Update ${DELIVERY_FILE} as implementation evolves"
echo "  4. Finalize ${PR_FILE} before opening PR"